### ISSUE TITLE
Cant find config option for fallen leaves/twigs and falled trees

### ISSUE THREAD

**Issue by R4lfXD** [mc-jt9/ProjectVibrantJourneys#106]
Hello, I'm editing the config to optimize it for Biomes O' Plenty and can't find these options. Are they hidden under something else or don't exist?

**Comment by OrderedChaos-Dev** [comment]
They are all grouped under their respective tree, e.g. oakTreesBiomes option is also the one for fallen leaves/twigs/trees.

**Comment by R4lfXD** [comment]
Thanks for the reply! Is that a thing for the Sparse versions as well?

**Comment by OrderedChaos-Dev** [comment]
Yes, although some things are inconsistent. For example, trees with their own biomes (redwoods, willows, etc) can only generate in those biomes. If you add say the plains biome to the redwoods option, you would see redwoods twigs and leaves generate, but not trees.
This is mostly because I was lazy and also because the config is pretty messy since Forge hasn't added in the in-game config menu yet.

**Comment by R4lfXD** [comment]
Yeah, I reordered the config only to then find out that it resets when you load the game lol. So I'm using excel for now.
Anyway, thanks! If you want I can upload the config somewhere so you can add it as an optional optimization for Biomes O'Plenty (even though I disabled almost all of your biomes to no have double of the same type).

**Comment by OrderedChaos-Dev** [comment]
Eventually I'll get around to adding proper support for Biomes O'Plenty, but it will be a separate mod instead to avoid bloat. I don't really know when I'll be doing that though.
