### ISSUE TITLE
Dynamic Trees

### ISSUE THREAD

**Issue by sfiomn** [mc-jt9/ProjectVibrantJourneys#135]
Hello,

Do you think to add a compatibility with Dynamic Trees ?

DYnamic trees adds the concept of branches on which mushrooms don't spawn correctly :
![image](https://user-images.githubusercontent.com/38457246/117072013-24101000-ad30-11eb-8560-ebbcfd7c54a9.png)

Would be so great

**Comment by OrderedChaos-Dev** [comment]
As far as making them actually attach to those blocks, it is a lot of work to do since the branches/logs are non-cubic. I've made a change for the next update to stop spawning the bark mushrooms on logs that are not a full cube to prevent weird generation like that, but I can't really solve the visual issues.
