### ISSUE TITLE
Leaves patches (from BYG) spawn on top of vibrant blocks

### ISSUE THREAD

**Issue by Krampus69** [mc-jt9/ProjectVibrantJourneys#152]
Hello hello :)
I'm using projectvibrantjourneys-1.16.5-3.1.0 and there are some leaves that spawn on top of the vibrant journeys blocks.
I'm not sure if this has to be said here or on the Biomes You'll Go github, either way I'm still giving the info about this issue.

Your mod is really great, haven't downloaded the latest version because it adds lots of biomes and trees that are already in my game (I don't know if you can disable the biomes function). Keep up the good work, thank you :)

**Comment by Krampus69** [comment]
![2021-08-03_20 54 27](https://user-images.githubusercontent.com/81943963/128071283-bda3a3ef-698c-4dc7-9206-2893cdbcc0c8.png)

**Comment by OrderedChaos-Dev** [comment]
Oh, it's because the blocks are treated like dirt blocks so the leaves can generate on top, which is my fault. Also, there are options to disable the new biomes, but I forgot to add options to disable trees that spawn in vanilla biomes. I'll add those options as well as a fix for this in this week's release.

**Comment by OrderedChaos-Dev** [comment]
Fixed, hopefully
