### ISSUE TITLE
Leaves floating over pebbles

### ISSUE THREAD

**Issue by Krampus69** [mc-jt9/ProjectVibrantJourneys#166]
Hello, this bug occurs when using ByG with vibrant in cherry biome
![2021-10-24_03 05 56](https://user-images.githubusercontent.com/81943963/138576288-56412efd-ec6f-4d19-ac8b-6391cff5b382.png)
s

Leaves carpet floats on top of pebbles.

**Comment by vgrynch** [comment]
This probably may be fixed by correcting some attributes of world gen via a data pack. I also trying to find a solution to this as it is not only that. Sometimes it looks worse, for example:
![2023-08-12_13 43 04](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/assets/46818018/aeaec0a2-263e-4776-a041-98e9e5325c78)

**Comment by OrderedChaos-Dev** [comment]
At one point I fixed this, no idea what version though. But closing as stale
