### ISSUE TITLE
Serene Seasons and BOP compat

### ISSUE THREAD

**Issue by ekiplier** [mc-jt9/ProjectVibrantJourneys#170]
I know this is very unlikely to ever happen, and it sounds very ambitious, but would it be possible to integrate PVJ with BOP and Serene Seasons? I assume the Serene Seasons integration would be much easier as you'd only need to apply different colours to PVJ leaves for each season/sub season. The BOP integration would add fallen leaves to BOP trees and maybe some twigs too.

**Comment by OrderedChaos-Dev** [comment]
Not sure how Serene Season works, I remember playing with it once when it was first released and I thought they dropped support for it a while ago. I'll look into how to integrate PVJ with it. For BoP, there used to be full integration with it but I dropped it because of how much of a pain it was. The assets are still around somewhere, I need to find them. For something like that I would do a separate mod to avoid cluttering up this one.

It's not unlikely, especially since of a lot of people like to combine this with BoP for some of their trees and biomes. I also want to do compatibility addons with Dynamic Trees, when I have the time, as well as the Abnormals mods.
