### ISSUE TITLE
Structures Spawn

### ISSUE THREAD

**Issue by SaucissePuree** [mc-jt9/ProjectVibrantJourneys#26]
Hi, i have a problem, not really a bug:
I have a lot of mods that spawn structures (houses), and most of them spawn 1 block over the ground because of those stone/bone piles from your mod.
May be changing the load priority of PVJ to lower could resolve this ?
I'm not a modder, and i don't even know if it's doable...
Thank you.

**Comment by mc-jt9** [comment]
That might be a problem on the other end, with the structure spawning mods. The blocks you mentioned have extra code that tells the game its properties so that it can be replaced by blocks from a structure. When a mod generates structures, it should have checks during generation to make sure the structure can generate properly.
