### ISSUE TITLE
possible issue with BOP and the boreal forest

### ISSUE THREAD

**Issue by xkforce** [mc-jt9/ProjectVibrantJourneys#41]
**Describe the bug**
game crashes w/ crashlog provided below.  Appears to be related to the boreal forest biome and biomes o plenty.  I:borealForestWeight=0 in the config which should disable the biome.

**Crash Logs**
https://pastebin.com/46ZnkVxR

**Comment by mc-jt9** [comment]
Yes, sorry will fix

**Comment by mc-jt9** [comment]
It's crashing because pineDensity is set to something less than 1, which I overlooked. The snowy boreal forest and alpine heights draw from the same BiomeBorealForest class. The temporary solution is to set pineDensity to 1, which will still disable the pine trees, or disable the snow boreal forest and the alpine heights.

There are some things I haven't caught yet, sorry for the bugs.

**Comment by mc-jt9** [comment]
Fixed in 1.6.0 i hope
