### ISSUE TITLE
[Compatibility] Game Crash Using Mystical Grill if Inspirations Mod is Installed

### ISSUE THREAD

**Issue by JoelZBub** [mc-jt9/ProjectVibrantJourneys#88]
**Description of Issue**
Forge Version : 14.23.5.2838
Inspirations Version : 1.12.2-0.2.8
Project: Vibrant Journeys Version : 1.12.2-1.6.4

If Inspirations is installed, the Mystical Grill operates until the placed ingredient changes to a cooked item, then the game crashes (Integrated server crash in single player, dedicated server crash in multiplayer.) When re-entering the game, the cooked item on the grill has no potion effects added.

**Steps to Reproduce:**

1. Install PVJ and Inspirations
2. Construct and use a Mystical Grill 

**Crash Logs**
https://hatebin.com/dzfjfowhum

**Other Notes**
Issue also reported to Inspirations issue tracker: https://github.com/KnightMiner/Inspirations/issues/150

**Comment by JoelZBub** [comment]
Inspirations developer has proposed a fix for this issue.
https://github.com/KnightMiner/Inspirations/issues/150#issuecomment-563426604

**Comment by mc-jt9** [comment]
Yeah I did a big dumb. The 1.12 version is no longer being developed and a 1.15 version is on the way, but the mystical grill is being benched.

**Comment by Norfried** [comment]
Here's what I discovered regarding this crash.

Just use a magma block instead of fire beneath the cauldron, and all should go well.
By default, the Inspirations mod uses the vanilla fire block in it's config to bring the water in a cauldron to a boil, and when the mystical grill activates and attempts to remove a bottle's worth of boiling water from the cauldron, that's what causes the game to crash.

One way to fix this would be to change Inspiration's config to exclude vanilla fire, and add a different block to boil water instead (lava for example). Or avoid using vanilla fire with a mystical grill like the plague, but that's not an easy guarantee on a server.

I know this issue page is dead, but for all you 1.12.2 users out there, please do take note of this.
