### ISSUE TITLE
Suggestion: mobs

### ISSUE THREAD

**Issue by maddikarp** [mc-jt9/ProjectVibrantJourneys#95]
Hi! Your mod is one of my favorites so far, as I really only want improvements to vanilla mc. 
I have a lot of ideas for/problems with mobs:
1. Replace vanilla farm mobs (cows, pigs, sheep, chickens) with equivalent wild versions and put them in appropriate biomes instead of having them spawn everywhere. Ex, finding boars (pigs) in forests and finding buffalo (cows) in plains. The originals can still be found exclusively on village farms, similar to how domestic cats are found. It feels silly and too easy to find random farm animals in the wild. Maybe add domestication gameplay feature, similar to turning ocelots to cats but more well thought out???
2.  More biome-specific fauna. I feel like each biome should have a set group of animals. The forests are getting better but could still use deer, while others like the desert, ocean, mountains, swamp and arctic feel ignored. Some ones I would really like to see are deer, songbirds, snakes, sharks, whales. I like to choose animals that are common and have some sort of variation everywhere in the world.
3. More fun mini-bosses, hostile or even neutral mobs!!! I love your addition of ghosts and think there needs to be more fun creepy/mythical mobs that add to the charm of minecraft.

**Comment by OrderedChaos-Dev** [comment]
I was actually thinking about adding those things, with rams in mountains to replace sheep, zebras to replace horses in savannas, etc, along with deer and other animals. The issue is that I am not very good at modelling mobs and making textures for anything, and also that I am thinking that might deserve to be its own separate mod.

I am currently working on porting everything over to 1.15. There have been some new content added along with it, but nothing substantial until I can get everything ported. Since you liked the ghosts, I'll also mention that the shade mob is now biome-restricted to jungles and swamps, but other biomes get their own variant such as banshees, haunts, nightmares, etc. I have yet to port the goon and watcher over to 1.15, but once that is done, I also have a few other creepy-ish mobs I hope to add in.

My experience with 1.15 modding so far has shown me that it is much more smooth and reliable than 1.12. I only have time to develop on one version, so I've picked 1.15. I will try to push out a beta release by the end of the week with most of the content ported, and hopefully a full release by the end of the month/early Feb.

**Comment by maddikarp** [comment]
Awesome!! I'll be really happy to play with those in my game. Can't wait to see what you come up with 😊

**Comment by OrderedChaos-Dev** [comment]
Putting this to planned list
